### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by CrazyPython** [ShprAlex/SproutLife#1]
This project has lots of potential. This project seems semi-dead. No PRs or issues have been created. 

Suggestions
- allow customized seeding
- inspect organisms and see their genome
- option to allow seed to delay before sprouting - room is needed
- a superspeed option

**Comment by witzatom** [comment]
Very cool stuff, I thought about some similar system just today. Came home, googled to see if somebody already made it and here I am. Nice work!

**Comment by ShprAlex** [comment]
Thanks guys! I appreciate the feedback.
