### ISSUE TITLE
Error during initialization of VM

### ISSUE THREAD

**Issue by Shawoll** [ShprAlex/SproutLife#18]
Hi, great project, love the idea.
I would like to run the jar file with `java -jar -Xmx2g SproutLife.jar`, but when I do, I receive: &nbsp;

`java -jar -Xmx2g SproutLife.jar`
`Error occurred during initialization of VM`
`Could not reserve enough space for 2097152KB object heap`.

What can I do to make it run? Thank you in advance.

**Comment by ShprAlex** [comment]
Thanks @Shawoll ! I think you can just do `java -jar -Xmx1024m SproutLife.jar`. or `-Xmx512m`

There are also some tips here ... let me know how it works out, thanks.
https://java2blog.com/could-not-reserve-enough-space-for-object-heap/

**Comment by ShprAlex** [comment]
Btw, @Shawoll you're better off rebuilding the latest from source code. I need to create a new release which has much improved color rendering. That's the instructions on the [readme](https://github.com/ShprAlex/SproutLife#readme) ending with `mvn exec:java`

**Comment by Shawoll** [comment]
Thanks @ShprAlex ! Works like a charm with `-Xmx1024m` . I'll definitely build my own version and play around. Fascinating topic and nice coding Alex. Bless you and thank you for resolving my problem. I am closing this issue.
